# Generated by Django 6.0.4 on 2026-04-22 10:00

import blogAssignment.services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(upload_to=blogAssignment.services.models.blog_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='blogextraimg',
            name='image',
            field=models.ImageField(upload_to=blogAssignment.services.models.blog_extra_upload_path),
        ),
    ]
