# Generated by Django 6.0.4 on 2026-04-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_blog_cover_image_alter_blogextraimg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
